services:
  mujoco-base:
    build:
      context: ..
      dockerfile: docker/Dockerfile.mujoco
    image: mujoco-base
    container_name: mujoco-base
    # Note: `privileged` is not the safest, but it is an easy way to give real-time privileges to the container.
    privileged: true
    network_mode: host
    environment:
        - DISPLAY=${DISPLAY}
    volumes:
      - ../robot_motion:/workspace/robot_motion
      - ../robot_motion_interface:/workspace/robot_motion_interface
      - ../robot_description:/workspace/robot_description
      # Xhost forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true 